# come risolvere l'errore
# devo aggiungere le path dei volumi nei container qua sotto ma ora non ne ho voglia

version: '3'
services:

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/usr/share/nginx/html

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - wordpress_volume:/var/www/wordpress
    environment:
      MYSQL_HOST:     ${MYSQL_HOST}
      WP_DB_NAME:     ${WP_DB_NAME}
      WP_DB_USR:      ${WP_DB_USR}
      WP_DB_PWD:      ${WP_DB_PWD}
      DOMAIN_NAME:    ${DOMAIN_NAME}
      WP_TITLE:       ${WP_TITLE}
      WP_ADMIN_USR:   ${WP_ADMIN_USR}
      WP_ADMIN_PWD:   ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR:         ${WP_USR}
      WP_PWD:         ${WP_PWD}
      WP_EMAIL:       ${WP_EMAIL}

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception
    ports:
      - 3306:3306
    volumes:
      - mariadb_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      DB_NAME: ${WP_DB_NAME}
      DB_USER: ${WP_DB_USR}
      DB_PASSWORD: ${WP_DB_PWD}
      DB_HOST: ${MYSQL_HOST}

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MARIADB_HOST_VOLUME_PATH}

  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${WORDPRESS_HOST_VOLUME_PATH}

networks:
  inception:
    driver: bridge
    name: inception

