version: '3'
services:

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - "wordpress_volume:/var/www/html"

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - "wordpress_volume:/var/www/html"
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception
    ports:
      - 3306:3306
    volumes:
      - "mariadb_volume:/var/lib/mysql"
    env_file:
      - .env

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MARIADB_HOST_VOLUME_PATH}

  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${WORDPRESS_HOST_VOLUME_PATH}

networks:
  inception:
    driver: bridge
    name: inception

